### ISSUE TITLE
Data 

### ISSUE THREAD

**Issue by Gupta-Pankhuri** [datacenter/aci-monitoring-stack#24]
Hi,

I am currently deploying a solution to fetch ACI metrics and have successfully retrieved data for the sd(service discovery). However, I am encountering issues when attempting to fetch data for the following classes:

--> node_interface_info: It seems that I am receiving duplicate data.
![image](https://github.com/user-attachments/assets/25d1d22b-2ff1-4c28-8caf-c72017ffe348)
--> topSystem: I am unable to retrieve any metrics for ACI.
![image](https://github.com/user-attachments/assets/58fa59f8-a7b9-4e84-9ab0-03eebc45d7fa)
--> SD - data is available
![SD](https://github.com/user-attachments/assets/95448fbb-057a-464c-8d26-3e9e4b695d32)

Could you please provide guidance on where I might be making a mistake and suggest potential solutions for these issues?

**Comment by camrossi** [comment]
Hi @Gupta-Pankhuri !

let start with the easy one ;) 
- The `queries` is not the ACI Class but this paramenter needs to match the queries name defined in the aci-exporter config file.  for example if you are probing an APIC you would say `queries=controller_topsystem` and for a switch `queries=node_topsystem` you can see this in this the config file: [node.yaml](https://github.com/datacenter/aci-monitoring-stack/blob/main/charts/aci-monitoring-stack/config.d/node.yaml )

- node_interface_infos: What is 172.16.121.2? node_interface_infos Needs to be directed to the IP address of a switch no to the APIC. I get a similar output if I use the APIC IP as target. 
The whole idea of the stack is to distribute the queries directly to the switches not to overburden the APIC.

If you deploy the stack this is taken care automatically by the prometheus config. Are you deploy the stack or just aci-exporter?

**Comment by Gupta-Pankhuri** [comment]
172.16.121.2 is my APIC-controllers IP, if not APIC IP address then what to use which config file to use and how to use the exporter,
I'm currently running the exporter with **./build/aci-exporter -config fab1.yaml** and fab1.yaml is my config file where I'm giving APIC's information.

**Comment by camrossi** [comment]
Broadly speaking if you want to re-use the queries from this repo if a query start with 

- `node_xxxxxx` then it has to be sent to the node ip. i.e. `probe?target=fab2&node=192.168.68.61&queries=node_interface_info` where `192.168.68.61` is the management IP of the switch. 
- If does not start with `node` then is an APIC query and you do not need to add `node` in the probe URL.

If you want to use just the exporter as said please read the documentation of the aci-exporter and start getting familiar with it with simple queries. 

You could try to follow this example as well: https://github.com/datacenter/aci-monitoring-stack/blob/main/docs/development.md#aci-exporter-and-prometheus

Where I try to guide you through configuring the exporter.

The aci-exporter repo also has some examples that you could use get yourself familiar with.

**Comment by Gupta-Pankhuri** [comment]
According to the mentioned example I just didn't understand that where exporter needs to be run and setup should be done because prometheus and  ACI node are different in my case so I was running exporter and config files from prometheus node. Therefore, curl "http://aci-exporter-ip:9643/probe?target=fab1&node=192.168.68.8&queries=node_interface_info" in this API I'm confused if in aci-exporter-ip I should enter prometheus IP or APIC's IP if I'm running exporter on prometheus node with config file consisting of APIC's detail.

**Comment by camrossi** [comment]
If you look at this section in the read.me https://github.com/datacenter/aci-monitoring-stack?tab=readme-ov-file#aci-object-scraping you can see that prometheus polls ACI exporter so in the example:

`"http://aci-exporter-ip:9643/probe?target=fab1&node=192.168.68.8&queries=node_interface_info"` prometheus is the one what would make this HTTP request. 

- `aci-exporter-ip` is the IP address of the server where the `aci-exporter` is running 
- `target` is the fabric name as defined in the`aci-exporter` config 
- `node` is the IP address of the switch you are polling the data from. 
- `prometheus` can run on the same server as the `aci-exporter-ip` or anywhere really

**Comment by Gupta-Pankhuri** [comment]
Thanks for your suggestion, I'm now able to fetch data but I'm facing one more issue which is when I merged all the yaml files in config.d folder to my main yaml which I'm using while running the exporter I'm getting data for some but for few I'm not getting data like from vlan.yaml file I'm not getting any data for any paramter also in system.yaml file getting data for 2 parameter for 2 classes but not for others, I'm not sure about how to troubleshoot it and where the issue is. 
Thank you for your kind support.

**Comment by camrossi** [comment]
If you are using my configs the VLAN queries are supposed to be directed at the switches. 
Last I checked you where just using the APICs? 

Can you share more details please also if you are deploying just the aci-exporter without using the full monitoring stack I will not be able to assist you further as this repo is specifically for the full monitoring stack.

**Comment by bharat4212** [comment]
@camrossi , i am getting the same issue, i am using Prometheus, Grafana and exporter provided by you. In data i can see all the switches which auto discovered, as i have provided the ACI credentials. But i can't see the data related to switches like vlan.

As per your above comment queries will automatically goes to switch, for auto discovered switches via aci-exporter. But i am not able to see the data. Need your support on the same. Please note i am not using full stack over here.

Let me know if we can meet on any channel as well.

//Bharat

**Comment by Gupta-Pankhuri** [comment]
> If you are using my configs the VLAN queries are supposed to be directed at the switches. Last I checked you where just using the APICs?
> I've used all your yaml files from config.d folder and made a single yaml with creds of APIC controller and configs and I'm passing it while running the exporter, I've integrated it with prometheus as well and I'm getting data for all switches, etc
Prometheus UI :- ![image](https://github.com/user-attachments/assets/8625fb5b-51ad-43aa-b02b-64aca7098a68)

> Can you share more details please also if you are deploying just the aci-exporter without using the full monitoring stack I will not be able to assist you further as this repo is specifically for the full monitoring stack.
> I'm using aci-exporter in which I'm mentioning creds of APIC controller in the config yaml file which I'm using as config parameter
How I'm running aci-exporter :- ![image](https://github.com/user-attachments/assets/372fb48c-5789-4a39-a1b8-38c49e8509af)
Config file :- ![image](https://github.com/user-attachments/assets/5cdaaaa3-e0ae-473e-929a-b01b7a450d95)

Note:- In our enviournment APIC controller is capable of fetching all the data for all switches, etc

Please let me know if any other information is required.

**Comment by camrossi** [comment]
Closing this issue now, I will not provide support for custom integrations
